title: "Arduino Curriculum"
theme: jekyll-theme-cayman
include: ["assets/css"]
description: "Hands-on Arduino lessons for secondary students"

url: "https://<your-username>.github.io"
baseurl: "/arduino.journey"

# Author info (optional)
author:
  name: "Henrik"
  bio: "Secondary school(Middle-School) technology teacher"

# force rebuild
